version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "8e:c6:0d:8f:6c:1d:e4:02:31:ce:8d:a9:13:53:1f:22" 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main.yml
              
  test_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "8e:c6:0d:8f:6c:1d:e4:02:31:ce:8d:a9:13:53:1f:22" 
        - run:
            name: test connection
            command: |
               which ssh 
               
# Sequential workflow
workflows:
  # Name the workflow
  infrastructure_workflow:
    jobs:
      - test_infrastructure
