# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    description: "A very simple command for print workflow id"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >> $CIRCLE_WORKFLOW_ID
jobs:
  test-print:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - run: exit 1
      - run:
          command: print_pipeline_id.to workflow
          when: on_fail
     
workflows:
  # Name the workflow "welcome"
  hello-world:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - test-print