---
- name: "update apt packages."
  become: yes
  yum:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  yum:
    name: "*"
    state: latest

- name: "remove dependencies that are no longer required"	
  become: yes
  yum:
    autoremove: yes

- name: "Download setup package"
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /tmp/setup_14.x

- name: "install nodejs repo"
  become: yes
  ansible.builtin.command: sudo bash /tmp/setup_14.x

- name: "install dependencies."
  become: yes
  yum:
    name: "nodejs"
    state: latest

- name: "install pm2"
  become: yes
  npm:
    name: "pm2"
    global: yes
    production: yes
    state: latest

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
